#!/bin/bash
set -e

mysql --protocol=socket -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL
SET old_passwords=0;
CREATE USER '$LEAN_DB_USER'@'%' IDENTIFIED BY '$LEAN_DB_PASSWORD';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS \`$LEAN_DB_DATABASE\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL ON \`$LEAN_DB_DATABASE\`.* TO '$LEAN_DB_USER'@'%';
FLUSH PRIVILEGES;
EOSQL