version: "3.9"
services: 
    haproxy:
        build:
            context: ./
            args:
                PUBLIC_DOMAIN: "${PUBLIC_DOMAIN}"
                USER_UID: "${MY_UID:-1000}"
                USER_GID: "${MY_GID:-1000}"
            dockerfile: ./haproxy.Dockerfile
        hostname: ha01.${PUBLIC_DOMAIN}
        restart: on-failure
        user: "${MY_UID:-1000}:${MY_GID:-1000}"
        environment:
            - PUBLIC_DOMAIN="${PUBLIC_DOMAIN}"
            - USER_UID="${MY_UID:-1000}"
            - USER_GID="${MY_GID:-1000}"
        ports:
            - "${PUBLIC_ADDRESS}:80:80"
            - "${PUBLIC_ADDRESS}:443:443"
        depends_on:
            - gitea
            - leantime
        volumes:
            - logs:/var/log
        secrets:
            - ssl_bundled
    gitea:
        build:
            context: ./
            args:
                VERSION: "${GITEA_VERSION}"
            dockerfile: ./gitea.Dockerfile
        hostname: gitea.${PUBLIC_DOMAIN}
        restart: always
        ports:
            - "${LOCAL_ADDRESS}:23000:3000"
            - "${LOCAL_ADDRESS}:2222:22"
        environment:
            - GITEA_CUSTOM=/data
        depends_on:
            - mariadb
        volumes:
            - logs:/var/log
            - gitea-data:/data
            - gitea-config:/etc/gitea
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ./gitea/app.ini:/etc/gitea/custom/conf/app.ini
            - ./gitea/app.ini:/data/conf/app.ini
    leantime:
        image: leantime/leantime:latest
        build:
            context: ./
            args:
                LEAN_VERSION: "${LEAN_VERSION:-3.3.3}"
            dockerfile: ./leantime.Dockerfile
        restart: unless-stopped
        hostname: db.${PUBLIC_DOMAIN}
        env_file: 
        - ./leantime/.env.lean                                         # Environment file with settings
        volumes:
        - ./leantime/.env.lean:/var/www/html/config/.env
        - leantime_public_userfiles:/var/www/html/public/userfiles     # Volume to store public files, logo etc
        - leantime_userfiles:/var/www/html/userfiles                   # Volume to store private user uploaded files
        ports:
        - "${LOCAL_ADDRESS}:20080:80"                                  # The port to expose and access Leantime
    mariadb:
        image: mariadb:${MARIADB_VERSION}
        hostname: db.${PUBLIC_DOMAIN}
        ports:
            - "${LOCAL_ADDRESS}:43306:3306"
        restart: 'always'
        volumes: 
            - db:/var/lib/mysql
            - logs:/var/log
            - ./mariadb/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
            MARIADB_AUTO_UPGRADE: 1
            GITEA_DB_NAME: "${GITEA_DB_NAME}"
            GITEA_DB_USER: "${GITEA_DB_USER}"
            GITEA_DB_PASSWORD: "${GITEA_DB_PASSWORD}"
            LEAN_DB_DATABASE: "${LEAN_DB_DATABASE}"
            LEAN_DB_USER: "${LEAN_DB_USER}"
            LEAN_DB_PASSWORD: "${LEAN_DB_PASSWORD}"
secrets:
    ssl_bundled:
        file: ./common/ssl/bundle.pem
volumes:
    db: 
        name: "devbelt-db"
    logs:
        name: "devbelt-logs"
    gitea-data:
        name: "devbelt-gitea-data"
    gitea-config:
        name: "devbelt-gitea-config"
    leantime_userfiles:
        name: "devbelt-leantime-userfiles"
    leantime_public_userfiles:
        name: "devbelt-leantime-public-userfiles"